"weaponManager__Q33scn4step9ComponentFv" = 0x8023f28c;
"__ct__Q43scn4step6weapon4DescFQ43scn4step6weapon4KindUlQ43scn4step5ostop4FlagRCQ33hel4math7Vector2RCQ33hel4math7Vector2RQ25ocoll5Owner" = 0x80610830;
"request__Q43scn4step6weapon7ManagerFRCQ43scn4step6weapon4Desc" = 0x80611614;
"t_obj__Q43scn4step4hero25" = 0x804fced4;
"heapName__Q23mem14HeapCompactionCFRCQ44nrel6devkit7heapmap7HeapMap" = 0x801cae04;
"internal_getArg_addr__Q26mintvm13MintFuncProxyCFUi" = 0x801a02e8;
"addNativeFunction__Q26mintvm14VMFunctionListFPCcPFRQ26mintvm13MintFuncProxy_v" = 0x801d8c28;

"vanilla_start" = 0x80006310;